### ISSUE TITLE
Strange 1px black - <custom-dropdown>

### ISSUE THREAD

**Issue by mohamedgeemi** [AutoScout24/showcar-ui#210]
There's a strange black 1px on the right of showcar-ui custom dropdown menus. This only happens in Mac Safari browsers.

![safari_issue](https://user-images.githubusercontent.com/13333655/105195635-1ba61780-5b3b-11eb-89a4-1b82e6acade5.png)

**Comment by rowantower** [comment]
Solved, please reach us back if you still experience problems
